<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>8e7f8c58-b6d1-499a-b7f6-3053377095dc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\21T1020526.Shop\21T1020526.Shop.csproj" />
    <ProjectReference Include="..\SV21T1020516.Shop\SV21T1020516.Shop.csproj" />
  </ItemGroup>

</Project>
